services:
  tournament-manager:
    container_name: tournament-manager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./:/opt/app-root/src
    environment:
      - DATABASE_URL=postgres://pkd:pswd@postgres:5432/pkd_tournaments

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pkd}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pswd}
      POSTGRES_DB: ${POSTGRES_DB:-pkd_tournaments}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
volumes:
  postgres:
