FROM golang:1.24 AS builder

WORKDIR /opt/app-root/src
COPY . .

RUN mkdir out
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o out ./...

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /opt/app-root/src/out/cmd .

RUN chmod +x cmd

RUN adduser -D appuser
USER appuser

CMD ["./cmd"]
